function mex_concatenate_compiler()
    current_folder = fileparts(which(mfilename('fullpath')));
    
    mex_compiler( ...
        current_folder, ...
        'mex_concatenate', ...
        { ...
            fullfile(current_folder, '..', '..', 'concatenate.c')
        }, ...
        {'-R2018a'} ...
    );
end